image: docker:latest

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY  

services:
  - docker:18.09.1-dind

build:
  stage: build
  only:
    - master
  script:
    - docker build -t productservice inventoryservice/.
    - docker push productservice
