image: docker:latest

before_script:
  - docker info

services:
  - docker:18.09.1-dind

build:
  stage: build
  only:
    - master
  script:
    - docker build -t productimage:latest inventoryservice/.
    - docker tag productimage:latest vsr-kub005.informatik.tu-chemnitz.de:31000/productimage:latest
    - docker push vsr-kub005.informatik.tu-chemnitz.de:31000/productimage:latest
    
