image: docker:latest

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

services:
  - docker:18.09.1-dind

build-frontend:
  stage: build
  only:
    - master
  script:
    - docker build -t frontend:latest frontend/.
    - docker tag frontend:latest rakibul56/frontend:latest
    - docker push rakibul56/frontend:latest

build-inventoryservice:
  stage: build
  only:
    - master
  script:
    - docker build -t inventoryservice inventoryservice/.
